version: "3"

services:
  backend:
    container_name: backend
    build:
      context: backend/DriverManagement
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s dotnet DriverManagement.Api.dll
    ports:
      - "5000:80"
    depends_on:
      - db

  proxy:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    tty: true # -it
    ports:
      - "3001:3000"
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    build:
      context: frontend/driver-management
      dockerfile: Dockerfile
    tty: true
    entrypoint: docker-entrypoint.sh npm run dev -- --port 3001
    depends_on:
      - backend

  db:
    container_name: db
    image: postgres
    volumes:
      - .docker/.postgres:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drivers
    ports:
      - "2345:5432"

networks:
  driver-management-net:
    driver: bridge
