version: "3"

services:
  backend:
    container_name: backend
    build:
      context: backend/DriverManagement
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s dotnet DriverManagement.Api.dll
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    volumes:
      - .docker/.postgres:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DriverManagement
    ports:
      - "2345:5432"

networks:
  driver-management-net:
    driver: bridge
